// Celestial Cartographer - Data Part 2b: Asia continued (Countries 42–50)
(function(){
var _d=function(id,n,loc,cat,q,de,ld,dt,h,p,co,t){
  return {id:id,name:n,location:loc,category:cat,
    heroImage:"https://source.unsplash.com/3840x2160/?"+q,
    galleryImages:["https://source.unsplash.com/1200x1600/?"+q+",detail","https://source.unsplash.com/1200x1600/?"+q+",view"],
    description:de,longDescription:ld,details:dt,hours:h,price:p,coordinates:co,tip:t};
};
var _c=function(id,n,la,lo,r,co,de,te,cl,bi,dests){
  return {id:id,name:n,lat:la,lng:lo,region:r,coordinates:co,description:de,
    heroImage:"https://source.unsplash.com/3840x2160/?"+n.toLowerCase().replace(/ /g,'+')+",travel,landscape",
    terrain:te,climate:cl,biodiversity:bi,destinations:dests};
};
var more={
  "israel":_c("israel","Israel",31.05,34.85,"Middle East","31.0461° N, 34.8516° E",
    "A land of layered civilisations where ancient prophets walked, seaside modernity thrives, and the lowest point on Earth shimmers with salt.",
    "Coastal / Desert / Highland","Mediterranean / Semi-Arid","Mediterranean Shrubland",[
      _d("old-city-jerusalem","Old City of Jerusalem","Jerusalem","Sacred Historic City","jerusalem+old+city+dome+rock+walls+sacred",
        "A walled holy city shared by three world religions atop millennia of history.",
        "Within one square kilometre, the Old City holds the Dome of the Rock, the Western Wall, and the Church of the Holy Sepulchre. Every stone here resonates with sacred memory spanning thousands of years.\n\nThe narrow stone lanes of the souq bustle with pilgrims, vendors, and locals in a timeless daily rhythm. Arrive at dawn to witness the city stir to life before the crowds descend.",
        {"Site Type":"UNESCO World Heritage Site","Religion":"Judaism / Christianity / Islam","Best Time":"Spring (Mar–May)","Access":"Jaffa Gate or Damascus Gate","Language":"Hebrew / Arabic"},
        "Open 24 hours; individual sites vary","Free to enter (site fees vary)","31.7767° N, 35.2345° E",
        "Visit the Jewish Quarter's Cardo early morning for quieter exploration before tour groups arrive."),
      _d("masada-fortress","Masada Fortress","Dead Sea Region","Hilltop Fortress","masada+fortress+israel+dead+sea+desert+sunrise+aerial",
        "A dramatic mesa-top fortress where Jewish rebels made their last stand against Rome in 73 CE.",
        "Rising 400 metres above the Dead Sea, Masada's plateau holds Herod's palaces, Roman-era bathhouses, and a haunting history of siege and sacrifice. The Snake Path ascent at sunrise rewards with panoramic desert views.\n\nA cable car provides easy access for those who prefer not to hike. The surrounding desert landscape glows in hues of amber and gold at golden hour.",
        {"Site Type":"UNESCO World Heritage Site","Era":"Herodian / Roman","Elevation":"50 m below sea level (base)","Cable Car":"Available","Best Time":"October–April"},
        "8:00 AM – 4:00 PM (last entry)","₪29 adult","31.3155° N, 35.3535° E",
        "Take the Snake Path before 7 AM to beat the heat and catch a spectacular desert sunrise."),
      _d("dead-sea-israel","Dead Sea","Ein Bokek","Salt Lake","dead+sea+israel+floating+salt+crystals+sunset",
        "The world's lowest and saltiest body of water, where every visitor effortlessly floats.",
        "At 430 metres below sea level, the Dead Sea's hypersaline waters create a surreal floating experience unlike anywhere on Earth. Salt crystals encrust the shoreline in brilliant white formations.\n\nThe mineral-rich black mud is famed for skin-rejuvenating properties. Sunset paints the water in vivid oranges and purples against the Jordanian mountains opposite.",
        {"Salinity":"34% (ten times ocean average)","Elevation":"-430 m (lowest on Earth)","Best Time":"October–May","Nearby":"Masada, En Gedi","Water Temp":"25–35°C"},
        "Beach resorts open daily 8:00 AM – 6:00 PM","Free (public beaches); resort access ₪50–₪120","31.5590° N, 35.4732° E",
        "Cover any cuts before entering — the salt stings intensely. Rinse off immediately after to protect your skin."),
      _d("tel-aviv-promenade","Tel Aviv Promenade","Tel Aviv","Beachfront Promenade","tel+aviv+beach+promenade+mediterranean+sunset+city",
        "A vibrant Mediterranean seafront stretching through one of the Middle East's most dynamic cities.",
        "Tel Aviv's 14-kilometre promenade links golden sandy beaches, outdoor gyms, and buzzing café terraces facing the shimmering Mediterranean. It embodies the city's famously energetic, hedonistic character.\n\nThe adjacent Bauhaus-rich White City offers a UNESCO-listed architectural contrast just steps from the sand. Sunsets here, watched from a beachside bar, are reliably spectacular.",
        {"City Founded":"1909","UNESCO District":"White City (Bauhaus)","Beach Count":"14 public beaches","Vibe":"Cosmopolitan / Liberal","Best Time":"April–October"},
        "Public beaches open 24 hours","Free","32.0853° N, 34.7818° E",
        "Rent a Tel-O-Fun city bike to cruise the full promenade length in under an hour."),
      _d("caesarea-ruins","Caesarea Ruins","Caesarea","Roman Port City","caesarea+israel+roman+ruins+aqueduct+sea+ancient",
        "A breathtaking Roman harbour city where a 2,000-year-old aqueduct still stands beside the Mediterranean.",
        "Built by Herod the Great and named for Augustus Caesar, Caesarea was once Rome's grandest eastern port, complete with a theatre, hippodrome, and palace. Today the national park preserves these extraordinary ruins.\n\nThe Crusader-era harbour walls and partially submerged Roman breakwater add further layers of history. The site is walkable within a half-day and best visited in the soft late-afternoon light.",
        {"Era":"Roman / Byzantine / Crusader","Key Feature":"Herodian aqueduct & amphitheatre","Park Size":"3,770 acres","Nearby":"Tel Aviv (1 hr)","Best Time":"October–April"},
        "8:00 AM – 5:00 PM (Fri until 4:00 PM)","₪35 adult","32.5009° N, 34.9007° E",
        "The Roman amphitheatre hosts summer concerts — check the schedule for a magical evening performance.")
  ]),
  "uzbekistan":_c("uzbekistan","Uzbekistan",41.38,64.59,"Central Asia","41.3775° N, 64.5853° E",
    "The jewel of the ancient Silk Road, Uzbekistan dazzles with turquoise-tiled mosques, crumbling desert fortresses, and bazaars perfumed with saffron and dried apricots.",
    "Desert / Steppe / Mountain","Hot Continental Arid","Central Asian Desert & Steppe",[
      _d("samarkand-registan","Samarkand Registan","Samarkand","Silk Road Masterpiece","samarkand+registan+uzbekistan+mosaic+tile+blue+dome+silk+road",
        "Three colossal madrasas clad in dazzling cobalt tilework form the greatest ensemble of Islamic architecture in Central Asia.",
        "The Registan — meaning 'sandy place' — served as Samarkand's public square and intellectual heart during the Timurid golden age. Its three madrasas, built between the 15th and 17th centuries, display breathtaking geometric tilework.\n\nAt sunset the domes shift from cobalt to gold in a mesmerising display of light. The nightly sound-and-light show projects the complex's history onto its towering facades.",
        {"Built":"15th–17th century","Style":"Timurid Islamic","UNESCO":"World Heritage Site","City":"Samarkand (2,700 years old)","Best Time":"April–June, Sep–Oct"},
        "8:00 AM – 9:00 PM","UZS 80,000 adult","39.6542° N, 66.9757° E",
        "Arrive exactly at opening to photograph the empty square bathed in morning golden light."),
      _d("bukhara-old-city","Bukhara Old City","Bukhara","Ancient Islamic City","bukhara+old+city+uzbekistan+minaret+mosque+islamic",
        "One of Central Asia's best-preserved ancient cities, where medieval trading domes and minarets crowd a UNESCO-listed historic centre.",
        "Bukhara has been a centre of Islamic scholarship and commerce for over two millennia, and its old city retains a remarkable density of historic monuments. The Kalon Minaret, standing since 1127, once guided caravans across the desert.\n\nWinding alleys connect caravanserais, bathhouses, and covered bazaars still selling silk, spices, and handwoven carpets. Evenings in the central Lyabi-Hauz pond plaza are quietly magical.",
        {"UNESCO":"World Heritage Site","Key Monument":"Kalon Minaret (1127 AD)","Historic Buildings":"140+ monuments","Best Time":"April–June, Sep–Oct","Craft":"Silk, suzani embroidery"},
        "Sites open 9:00 AM – 6:00 PM","UZS 40,000–80,000 per site","39.7747° N, 64.4286° E",
        "Stay overnight — the old city after dark, lit by warm lamps with few tourists, is unforgettable."),
      _d("khiva-walled-city","Khiva Walled City","Khiva","Living Museum City","khiva+uzbekistan+walled+city+mudbrick+minaret+ancient",
        "A hauntingly intact desert fortress city where mud-brick walls enclose a skyline of turquoise minarets unchanged for centuries.",
        "Khiva's inner walled city, Itchan Kala, is so well-preserved it feels more museum than municipality. Over 50 historic monuments crowd within its crenellated mud-brick walls in the Khorezm oasis.\n\nThe unfinished Kalta Minor minaret, clad in brilliant turquoise tiles, was intended to be the world's tallest before the khan died. Sunrise from the city walls offers a cinematic panorama of the desert skyline.",
        {"UNESCO":"World Heritage Site (Itchan Kala)","Wall Height":"10 metres","Key Site":"Kalta Minor Minaret","Region":"Khorezm oasis","Best Time":"April–June, Sep–Oct"},
        "Open 24 hours; museums 9:00 AM – 6:00 PM","UZS 100,000 (combined ticket)","41.3775° N, 60.3639° E",
        "Buy the combined museum ticket at the east gate — it covers all major sites and saves significant money."),
      _d("tashkent-chorsu","Chorsu Bazaar","Tashkent","Central Asian Bazaar","tashkent+chorsu+bazaar+uzbekistan+dome+market+spices",
        "Tashkent's great domed market overflows with mountains of spices, dried fruits, and the everyday commerce of Central Asian life.",
        "The vast blue-domed Chorsu Bazaar has been Tashkent's commercial heart for centuries, filling multiple halls with vendors selling everything from samsa pastries to pyramids of crimson chilli. Its sensory intensity is overwhelming in the best possible way.\n\nThe surrounding neighbourhood retains a traditional Central Asian character distinct from Tashkent's Soviet-built centre. Morning visits catch the freshest produce and most authentic atmosphere.",
        {"Type":"Traditional covered bazaar","Specialties":"Spices, dried fruit, bread, meat","Location":"Old Town, Tashkent","Best Time":"Morning (7–11 AM)","Nearby":"Khast Imam complex"},
        "Daily 6:00 AM – 7:00 PM","Free entry","41.3264° N, 69.2293° E",
        "Try the fresh non flatbread and a bowl of lagman noodle soup from vendors inside for a cheap authentic breakfast."),
      _d("shakhrisabz-ruins","Shakhrisabz Ruins","Shakhrisabz","Timur's Birthplace","shakhrisabz+uzbekistan+ak+saray+ruins+timur+ancient+gate",
        "The birthplace of Timur the Great, where the colossal ruined gateway of his Ak-Saray Palace still towers over the ancient city.",
        "Shakhrisabz — meaning 'green city' — was Tamerlane's beloved hometown, and he commissioned a palace here intended to surpass Samarkand's grandeur. Only the 38-metre flanking towers of the Ak-Saray gateway survive, still awe-inspiring in their immensity.\n\nThe UNESCO-listed old town also contains Timur's mausoleum complex and the ruins of a congregational mosque. The relatively fewer tourists make for a more contemplative Silk Road experience than Samarkand.",
        {"UNESCO":"World Heritage Site","Key Ruin":"Ak-Saray Palace gateway (14th c.)","Distance":"80 km south of Samarkand","Era":"Timurid (14th–15th c.)","Best Time":"April–June, Sep–Oct"},
        "8:00 AM – 6:00 PM","UZS 50,000 adult","39.0567° N, 66.8350° E",
        "Combine with a day trip from Samarkand — the mountain drive through Takhta-Karacha Pass is scenic.")
  ]),
  "taiwan":_c("taiwan","Taiwan",23.70,121.00,"East Asia","23.6978° N, 120.9605° E",
    "A mountainous island of sublime gorges, misty alpine forests, night-market feasts, and a cultural richness that punches far above its size.",
    "Mountainous / Coastal","Subtropical / Tropical","Subtropical Broadleaf & Mixed Forest",[
      _d("taroko-gorge","Taroko Gorge","Hualien County","Marble Gorge","taroko+gorge+taiwan+marble+canyon+river+turquoise",
        "A cathedral of white and grey marble cliffs carved by the Liwu River into one of Asia's most spectacular gorges.",
        "Taroko National Park's centrepiece is a 19-kilometre gorge where sheer marble walls rise hundreds of metres above a jade-green river. Tunnels carved through living rock connect viewpoints along the Central Cross-Island Highway.\n\nThe Swallow Grotto and Tunnel of Nine Turns walking trails bring visitors face-to-face with the dramatic geology. Waterfalls cascade from clifftops and mist drifts through the canyon on cool mornings.",
        {"Park Area":"92,000 hectares","Rock Type":"Marble & metamorphic","Key Trail":"Tunnel of Nine Turns","Best Time":"October–April","Hazard":"Rock falls; hard hats recommended"},
        "Open 24 hours; visitor centre 8:30 AM – 5:00 PM","Free","24.1580° N, 121.6174° E",
        "Wear a hard hat on the Swallow Grotto trail — they are provided free at the trailhead and are genuinely necessary."),
      _d("sun-moon-lake","Sun Moon Lake","Nantou County","Alpine Lake","sun+moon+lake+taiwan+misty+mountains+reflection+temple",
        "Taiwan's largest alpine lake, encircled by forested peaks and wreathed in morning mist, mirrors pagodas and sky in perfect symmetry.",
        "At 748 metres elevation in central Taiwan, Sun Moon Lake is named for its two distinct lobes — the sun-shaped eastern section and the crescent moon-shaped western part. The surrounding forests are home to the Thao indigenous people.\n\nThe 33-kilometre lakeside cycling path is one of Taiwan's finest rides, passing temples, tea plantations, and hillside villages. Sunrise over the lake from Ci'en Pagoda is among the island's most iconic views.",
        {"Elevation":"748 m","Area":"7.93 km²","Indigenous People":"Thao","Best Time":"October–April","Activity":"Cycling, boat tours"},
        "Open 24 hours; attractions vary","NTD 200 scenic area fee","23.8600° N, 120.9175° E",
        "Rent a bicycle at the Shuishe pier for a leisurely full-lake loop — most rental shops open by 7 AM."),
      _d("alishan-forest","Alishan Forest Railway","Chiayi County","Mountain Forest","alishan+forest+taiwan+sea+of+clouds+sunrise+cedar+trees",
        "A high-altitude forest sanctuary famous for its ancient cedars, sea of clouds, and a narrow-gauge railway climbing through mountain mist.",
        "The Alishan Forest Recreation Area sits at 2,000–2,663 metres and is blanketed in towering red cypress and cedar trees some over 2,000 years old. The UNESCO-nominated Alishan Forest Railway is one of the world's great mountain train journeys.\n\nThe pre-dawn trek to Zhushan viewpoint rewards visitors with a breathtaking sunrise above an ocean of clouds. Cherry blossoms in March and April draw huge crowds but create a fairytale landscape.",
        {"Elevation":"2,000–2,663 m","Famous For":"Sea of clouds, sunrise, forest railway","Best Season":"Mar–Apr (cherry blossom), Oct–Nov","Train":"Alishan Forest Railway (1912)","Tree":"Sacred red cypress groves"},
        "6:00 AM – 10:00 PM","NTD 300 adult","23.5118° N, 120.8039° E",
        "Book the early morning forest railway to Zhushan well in advance — seats sell out weeks ahead during cherry blossom season."),
      _d("jiufen-old-street","Jiufen Old Street","New Taipei City","Mountain Village","jiufen+taiwan+lanterns+old+street+night+mountain+gold+rush",
        "A hillside gold-rush village of red lanterns and winding stone steps spilling down misty cliffs above the Pacific.",
        "Jiufen boomed during the Japanese colonial gold rush and retains its labyrinthine lanes of traditional teahouses, temples, and shops. The iconic red-lantern-lit alley is said to have inspired the spirit world in Miyazaki's Spirited Away.\n\nThe village is best explored in late afternoon as the lanterns glow against dimming skies and the East China Sea shimmers below. The A-Mei teahouse offers arguably the most atmospheric setting in all of Taiwan.",
        {"History":"Japanese colonial gold mining era","Famous For":"Red lanterns, sea views, teahouses","Best Time":"Weekday evenings","Distance":"40 km from Taipei","Film":"Inspired 'Spirited Away' aesthetics"},
        "Shops open daily 10:00 AM – 9:00 PM (later weekends)","Free to explore","25.1085° N, 121.8441° E",
        "Visit on a weekday — weekend crowds on the narrow stairs become almost impassably dense by midday."),
      _d("taipei-101","Taipei 101","Taipei","Supertall Tower","taipei+101+taiwan+skyscraper+night+lights+fireworks",
        "Once the world's tallest building, Taipei 101 pierces the skyline with bamboo-inspired geometry and hosts the world's most-watched New Year fireworks.",
        "Rising 508 metres in the heart of Taipei's Xinyi financial district, Taipei 101 held the title of world's tallest building from 2004 to 2010. Its eight stacked segments echo traditional Chinese pagoda architecture and bamboo symbolism.\n\nThe indoor observatory on the 89th floor and outdoor deck on the 91st offer sweeping views from the mountains to the sea. The building's 660-tonne tuned mass damper — a giant gold pendulum — is visible inside and is an engineering marvel.",
        {"Height":"508 m (101 floors)","Built":"2004","Observatory":"89th & 91st floors","Damper":"660-tonne gold pendulum","Best View":"Clear afternoon or night"},
        "Observatory 10:00 AM – 9:00 PM daily","NTD 600 adult","25.0338° N, 121.5645° E",
        "The outdoor 91st-floor deck gives a better photo experience than the indoor floor — wear a light jacket as it is always windy.")
  ]),
  "maldives":_c("maldives","Maldives",3.20,73.22,"South Asia","3.2028° N, 73.2207° E",
    "A necklace of coral atolls strung across the Indian Ocean, where overwater bungalows float above the clearest turquoise water on the planet.",
    "Coral Atoll / Lagoon","Tropical Maritime","Indian Ocean Coral Reef",[
      _d("north-male-atoll","North Malé Atoll","North Malé Atoll","Coral Paradise","maldives+overwater+bungalow+turquoise+lagoon+tropical",
        "The most accessible and resort-dense atoll in the Maldives, offering overwater bungalows above translucent turquoise lagoons.",
        "North Malé Atoll surrounds the capital island and contains some of the Maldives' most iconic luxury resorts, where glass-floored bungalows sit directly over living coral gardens. The lagoon's impossibly vivid turquoise colour comes from the shallow, sandy seabed.\n\nSnorkelling directly from your bungalow reveals turtles, reef sharks, and tropical fish. The atoll's proximity to Velana International Airport makes it the easiest Maldivian destination to reach.",
        {"Resort Count":"40+ (most in Maldives)","Water Visibility":"30+ metres","Marine Life":"Turtles, reef sharks, rays","Best Time":"November–April","Transfer":"Speedboat from airport (20–45 min)"},
        "Resort check-in from 2:00 PM; beach open 24 hrs","Resort rates from USD 400/night","4.1755° N, 73.5093° E",
        "Book overwater bungalows on the western side of the resort for the best sunset views from your deck."),
      _d("baa-atoll","Baa Atoll","Baa Atoll","UNESCO Biosphere","baa+atoll+maldives+manta+ray+snorkeling+coral+reef",
        "A UNESCO Biosphere Reserve where manta rays gather in the hundreds at Hanifaru Bay during the southwest monsoon.",
        "Baa Atoll's Hanifaru Bay is one of the world's greatest wildlife spectacles — during the southwest monsoon, hundreds of manta rays and whale sharks congregate in its shallow waters to feed on plankton. The bay is protected, limiting visitor numbers to preserve this phenomenon.\n\nThe atoll's remote resorts offer pristine house reefs with outstanding coral health. It remains less developed than North Malé Atoll, giving a more secluded Maldivian experience.",
        {"UNESCO":"Biosphere Reserve (2011)","Key Event":"Manta aggregation (Jun–Nov)","Marine Life":"Manta rays, whale sharks, turtles","Access":"Seaplane from Malé (30 min)","Best Time":"June–November (mantas)"},
        "Hanifaru Bay tours 6:00 AM – 6:00 PM","USD 35 bay entry fee","5.0500° N, 73.0000° E",
        "Book Hanifaru Bay snorkelling through your resort — independent access is restricted and guide registration is required."),
      _d("vaadhoo-bioluminescent-beach","Vaadhoo Bioluminescent Beach","Raa Atoll","Bioluminescent Beach","maldives+bioluminescent+beach+glowing+blue+stars+night",
        "A world-famous beach where bioluminescent phytoplankton paint the shoreline with electric blue starlight after dark.",
        "Vaadhoo Island in Raa Atoll hosts one of nature's most ethereal phenomena — Noctiluca scintillans phytoplankton that emit blue light when disturbed by waves, creating a glowing sea of stars at the water's edge. The effect is strongest on moonless nights.\n\nThe phenomenon is most reliable between June and October during peak plankton bloom seasons. Walking barefoot along the glowing shore is one of the most otherworldly experiences in the Indian Ocean.",
        {"Phenomenon":"Bioluminescent phytoplankton","Best Months":"June–October","Visibility":"Best on moonless nights","Species":"Noctiluca scintillans","Island":"Vaadhoo, Raa Atoll"},
        "Beach accessible 24 hours","Free (resort guests); day passes available","5.9897° N, 73.3753° E",
        "Check the lunar calendar and visit on a new moon night — any ambient light significantly diminishes the effect."),
      _d("male-fish-market","Malé Fish Market","Malé","Cultural Market","male+fish+market+maldives+tuna+fishermen+local+catch",
        "The throbbing commercial heart of the Maldives, where fishermen unload skipjack tuna by the tonne onto the capital's northern waterfront.",
        "Malé's fish market on the northern harbour is the daily economic engine of the nation, a visceral display of the Maldivian fishing culture that underpins the islands' identity beyond the resort world. Entire yellowfin tuna are cleaved and traded in minutes.\n\nThe market is most active in the early morning and late afternoon when fishing dhonis return. The surrounding streets host tea shops, local cafés, and the real Maldivian daily life rarely seen by resort-island visitors.",
        {"Type":"Traditional fish market","Main Catch":"Skipjack & yellowfin tuna","Best Time":"6–9 AM or 4–6 PM","Location":"Northern waterfront, Malé","Nearby":"Grand Friday Mosque"},
        "Daily 4:00 AM – 8:00 PM","Free","4.1742° N, 73.5109° E",
        "Visit Malé on a day trip from your resort — the contrast with the resort world gives the Maldives genuine cultural depth."),
      _d("ari-atoll-diving","Ari Atoll Diving","Ari Atoll","Dive Paradise","ari+atoll+maldives+whale+shark+diving+reef+crystal+clear",
        "The Maldives' premier diving atoll, renowned for reliable whale shark encounters and walls of pristine coral teeming with pelagic life.",
        "Ari Atoll stretches 90 kilometres and offers some of the Indian Ocean's most exceptional scuba diving, with whale sharks present year-round in the southern section around Rangali. Hammerhead sharks, thresher sharks, and enormous schools of fish frequent the outer reefs.\n\nThe atoll houses a range of resorts from accessible mid-range to ultra-luxury, making it suitable for divers of all budgets. The resident whale shark population at the South Ari Marine Protected Area is among the most accessible on Earth.",
        {"Dive Sites":"70+ named sites","Key Species":"Whale shark (year-round)","Visibility":"20–40 metres","Best Diving":"December–April","MPA":"South Ari Marine Protected Area"},
        "Dive operators run trips 7:00 AM – 5:00 PM","USD 80–120 per dive","3.8667° N, 72.8333° E",
        "South Ari's Maamigili area offers almost guaranteed whale shark sightings year-round — book a dedicated whale shark dive.")
  ]),
  "azerbaijan":_c("azerbaijan","Azerbaijan",40.14,47.58,"Caucasus","40.1431° N, 47.5769° E",
    "Where ancient fire-worshipping civilisations met the Silk Road and oil-boom modernity, Azerbaijan offers flaming towers, petroglyphs, and stained-glass palaces.",
    "Caucasian / Caspian Coastal","Semi-Arid / Alpine","Caucasian Mixed Forest",[
      _d("baku-flame-towers","Baku Flame Towers","Baku","Modern Icon","baku+flame+towers+azerbaijan+night+illuminated+caspian",
        "Three soaring LED-clad skyscrapers shaped like flames that light up Baku's skyline in homage to Azerbaijan's ancient fire-worshipping heritage.",
        "The Flame Towers rise 182 metres above the Caspian Sea city, their glass facades covered in 10,000 LED panels that animate enormous flames, Azerbaijani flags, and water ripples each evening. They have become the instantly recognisable symbol of modern Baku.\n\nThe towers are best viewed from the hilltop Upland Park, which also offers sweeping panoramas of the Old City below. The surrounding Baku Boulevard runs 3.5 kilometres along the Caspian waterfront.",
        {"Height":"182 m (tallest tower)","LED Panels":"10,000+","Built":"2012","Best Viewpoint":"Upland Park / Martyrs' Lane","Nearby":"Icheri Sheher Old City"},
        "Exterior visible 24 hours; LED show nightly from dusk","Free to view","40.3654° N, 49.8328° E",
        "The LED show runs continuously from sunset — climb to Upland Park by 7:30 PM to secure a front-row bench."),
      _d("gobustan-petroglyphs","Gobustan Rock Art","Gobustan","UNESCO Rock Art","gobustan+petroglyphs+azerbaijan+ancient+rock+art+desert",
        "A UNESCO-listed desert plateau covered in over 6,000 prehistoric rock carvings depicting the lives of people who lived here 40,000 years ago.",
        "Gobustan's rocky landscape holds one of the world's richest concentrations of petroglyphs, ranging from Palaeolithic hunters and dancers to boats, bulls, and celestial symbols. The museum at the site's entrance provides excellent context before exploring the open-air gallery.\n\nNearby mud volcanoes — Azerbaijan has the world's highest concentration — bubble and gurgle in an eerie landscape just kilometres away. The combination makes for one of the region's most unusual half-day excursions.",
        {"UNESCO":"World Heritage Site (2007)","Petroglyphs":"6,000+ carvings","Age":"Up to 40,000 years old","Nearby":"Mud volcanoes","Distance":"65 km from Baku"},
        "9:00 AM – 6:00 PM daily","AZN 4 adult","40.0764° N, 49.3781° E",
        "Hire a local guide at the entrance — they identify easily-missed carvings that solo visitors walk straight past."),
      _d("sheki-khans-palace","Sheki Khan's Palace","Sheki","Silk Road Palace","sheki+khans+palace+azerbaijan+stained+glass+frescoes+silk+road",
        "An 18th-century palace of extraordinary delicacy, its walls covered in intricate frescoes and stained glass assembled without a single nail.",
        "Built in 1762 for Huseyn Khan, this UNESCO-listed palace is famed for its shebeke — hand-cut stained glass windows of geometric complexity assembled from thousands of pieces without glue or nails. The interior walls are entirely painted in floral and hunting scene frescoes.\n\nSheki itself is a charming Silk Road town in the Caucasus foothills, famous for its baklava and traditional caravanserai. The surrounding chestnut forests are spectacular in autumn.",
        {"Built":"1762","UNESCO":"World Heritage Site","Key Feature":"Shebeke stained glass (no nails/glue)","City":"Sheki (NW Azerbaijan)","Local Specialty":"Sheki halva & baklava"},
        "10:00 AM – 6:00 PM (closed Mon)","AZN 5 adult","41.1993° N, 47.1701° E",
        "Photography inside the palace requires a separate fee — pay it, as the frescoes and stained glass are genuinely extraordinary."),
      _d("lahij-village","Lahij Village","İsmayıllı District","Artisan Village","lahij+village+azerbaijan+cobblestone+copper+craftsmen+mountain",
        "A remote Caucasian mountain village where copper craftsmen have hammered their ancient trade on cobblestone streets for over a thousand years.",
        "Lahij sits at 1,450 metres in the Caucasus and has been a renowned centre of copper craft since the medieval period. The village's single main street is lined with workshops where artisans beat intricate patterns into jugs, bowls, and samovars.\n\nThe village is also known for its unique Lahiji language, distinct from Azerbaijani, still spoken by its residents. The mountain setting above deep gorges makes the drive an attraction in itself.",
        {"Altitude":"1,450 m","Craft":"Copper smithing (1,000+ year tradition)","Language":"Lahiji (distinct dialect)","Distance":"170 km from Baku","Best Time":"May–October"},
        "Workshops open daily 9:00 AM – 7:00 PM","Free to explore","40.8658° N, 48.3692° E",
        "Buy directly from the craftsmen in their workshops — prices are far lower than in Baku souvenir shops for the same quality."),
      _d("yanar-dag-fire","Yanar Dag Eternal Fire","Baku","Eternal Natural Fire","yanar+dag+azerbaijan+eternal+natural+fire+hillside+night",
        "A hillside that has burned continuously for centuries from naturally seeping gas, venerated by ancient Zoroastrian fire-worshippers.",
        "Yanar Dag — meaning 'burning mountain' — is a natural gas seep on the Absheron Peninsula where a 10-metre wall of flame has burned continuously from the hillside, reportedly for centuries. Marco Polo documented similar fires in the region during his travels.\n\nAzerbaijan's Zoroastrian heritage placed fire at the centre of spiritual life, and this phenomenon explains why the country was historically known as the 'Land of Fire'. The site is most dramatic and photogenic after dark.",
        {"Translation":"Burning Mountain","Fuel":"Natural gas seep","Burn History":"Reportedly centuries uninterrupted","Distance":"25 km from Baku","Best Time":"Night visit"},
        "Open 24 hours; visitor area 9:00 AM – 10:00 PM","AZN 2 adult","40.5022° N, 49.8178° E",
        "Visit after dark — the 10-metre wall of flame photographs dramatically against a black sky and is far more impressive than by daylight.")
  ]),
  "mongolia":_c("mongolia","Mongolia",46.86,103.85,"Central Asia","46.8625° N, 103.8467° E",
    "The world's most sparsely populated country, a vast rolling steppe where nomadic herders still live in felt gers and the sky dominates everything.",
    "Steppe / Desert / Mountain","Continental Extreme","Central Asian Steppe & Gobi Desert",[
      _d("gobi-desert","Gobi Desert","Ömnögovi Province","Ancient Desert","gobi+desert+mongolia+sand+dunes+vast+khongoryn+els+camel",
        "One of the world's great deserts, where the Khongoryn Els sand dunes roar with wind and dinosaur fossils erode from the red canyon walls.",
        "The Mongolian Gobi spans 1.3 million square kilometres of steppe, saxaul scrub, and iconic sand dunes, making it the largest desert in Asia. The Khongoryn Els — the 'Singing Sands' — rise up to 300 metres and produce a deep resonant hum in strong winds.\n\nThe Flaming Cliffs at Bayanzag, where Roy Chapman Andrews discovered the world's first dinosaur eggs in 1922, glow orange and red at sunset. Camel riding and sleeping in nomadic ger camps are the authentic ways to experience this extraordinary landscape.",
        {"Area":"1.3 million km² (part in China)","Dune Height":"Up to 300 m (Khongoryn Els)","Famous For":"Dinosaur fossils, sand dunes, camels","Best Time":"May–June, Sep–Oct","Accommodation":"Nomadic ger camps"},
        "No fixed hours — natural site","Ger camp tours from USD 80/night","43.7944° N, 102.7028° E",
        "Book a multi-day ger camp tour rather than a day trip — the Gobi's magic is in the silence of overnight desert stars."),
      _d("khovsgol-lake","Khövsgöl Lake","Khövsgöl Province","Sacred Lake","khovsgol+lake+mongolia+clear+blue+taiga+forest+ger",
        "Mongolia's 'Dark Blue Pearl', a pristine alpine lake holding 2% of the world's fresh surface water, rimmed by taiga forest and snow-capped peaks.",
        "Khövsgöl Lake sits at 1,645 metres near the Russian border and stretches 136 kilometres through larch taiga, crystal clear to 25 metres depth. The lake is sacred to the local Dukha reindeer-herding people and to Mongolian shamanic tradition.\n\nHorseback riding, kayaking, and trekking connect the scattered ger camps along the shore. In winter the lake freezes solid enough for ice trucks and the annual ice festival, which draws travellers from around the world.",
        {"Area":"2,760 km²","Depth":"262 m (second deepest in Asia)","Water Clarity":"25 m visibility","Best Time":"June–September","Winter":"Frozen Jan–April"},
        "Open year-round; park gates 8:00 AM – 8:00 PM","MNT 3,000 park entry","51.0000° N, 100.5333° E",
        "Hire horses from local families rather than tour operators — it is cheaper, supports herders directly, and is a genuine cultural exchange."),
      _d("karakorum-ancient-capital","Karakorum","Övörkhangai","Mongol Empire Capital","karakorum+erdene+zuu+monastery+mongolia+ancient+capital+steppe",
        "The 13th-century capital of the Mongol Empire, now marked by the imposing walls of Erdene Zuu Monastery, the first Buddhist monastery in Mongolia.",
        "Founded by Ögedei Khan in 1220, Karakorum was for decades the administrative centre of the largest contiguous empire in history. Little survives above ground, but the National Museum of Mongolia and on-site exhibits illuminate the city's extraordinary cosmopolitan character.\n\nErdene Zuu Monastery, built in 1586 using stones from Karakorum's ruins, surrounds itself with 108 white stupas and remains an active religious site. The Orkhon Valley setting is spectacularly green in summer.",
        {"Founded":"1220 AD by Ögedei Khan","Empire":"Mongol (Genghis Khan dynasty)","Key Site":"Erdene Zuu Monastery (1586)","UNESCO":"Orkhon Valley (World Heritage)","Distance":"360 km from Ulaanbaatar"},
        "Museum 9:00 AM – 6:00 PM; monastery dawn–dusk","MNT 10,000 museum; MNT 5,000 monastery","47.1956° N, 102.8417° E",
        "Visit in July during Naadam celebrations when the steppe around Karakorum fills with wrestling, archery, and horsemanship competitions."),
      _d("orkhon-valley","Orkhon Valley","Arkhangai Province","UNESCO River Valley","orkhon+valley+mongolia+nomad+ger+waterfall+steppe+horses",
        "A UNESCO World Heritage river valley that has been Mongolia's pastoral heartland for over two millennia, dotted with nomadic gers and ancient monuments.",
        "The Orkhon River meanders for 1,124 kilometres through Mongolia's most historically significant landscape, past the sites of the Xiongnu, Turkic, and Mongol empires. The valley's rich grasslands have supported nomadic herders in an unbroken tradition spanning millennia.\n\nOrkhon Waterfall drops 20 metres over ancient lava flows into a spectacular basalt canyon in the upper valley. Multi-day horse treks through the valley are among Mongolia's finest wilderness experiences.",
        {"UNESCO":"World Heritage Site (2004)","River Length":"1,124 km","Key Feature":"Orkhon Waterfall & basalt canyon","History":"2,000+ years of nomadic habitation","Best Time":"June–September"},
        "Open year-round (winter access limited)","Free (ger camp fees apply)","46.7500° N, 102.5000° E",
        "A three-day horse trek from Kharkhorin to the waterfall is one of Central Asia's great off-road adventures — arrange at local ger camps."),
      _d("terelj-national-park","Terelj National Park","Töv Province","Granite Wilderness","terelj+national+park+mongolia+granite+rocks+ger+camp+horses",
        "A granite wilderness of bizarre rock formations and alpine meadows just 55 kilometres from Ulaanbaatar, the easiest taste of Mongolian steppe wilderness.",
        "Terelj's distinctive Turtle Rock, Monk's Rock, and other weathered granite outcrops rise from flower-filled meadows in a visually dramatic landscape. The park is easily reached from the capital and offers ger camps at every budget level.\n\nHorseback riding, hiking, and visits to nomadic families are the main activities. The Aryabal Meditation Temple perches high above the valley, reached by a staircase of 108 steps cut into the cliff.",
        {"Distance":"55 km from Ulaanbaatar","Key Rocks":"Turtle Rock, Monk Rock","Activity":"Horse riding, hiking, ger stays","Best Time":"May–October","Nearby":"Chinggis Khaan Statue complex"},
        "Open year-round; park gate 8:00 AM – 9:00 PM","MNT 3,000 park entry","47.9500° N, 107.4167° E",
        "Combine with a stop at the 40-metre Chinggis Khaan equestrian statue at Tsonjin Boldog on the drive from Ulaanbaatar.")
  ]),
  "laos":_c("laos","Laos",19.86,102.50,"Southeast Asia","19.8563° N, 102.4955° E",
    "The gentle landlocked heart of Indochina, where saffron-robed monks collect alms at dawn, the Mekong slides past temple towns, and waterfalls plunge through jungle.",
    "Mountainous / Mekong River Valley","Tropical Monsoon","Indochina Dry Evergreen Forest",[
      _d("luang-prabang","Luang Prabang","Luang Prabang Province","UNESCO Temple Town","luang+prabang+laos+monks+alms+giving+mekong+river+temples",
        "A UNESCO-listed royal capital where the daily alms-giving ceremony at dawn remains the most serene ritual in all of Southeast Asia.",
        "Luang Prabang sits on a peninsula between the Mekong and Nam Khan rivers, its streets lined with gilded temples, French colonial villas, and ancient stupas. The tak bat alms-giving procession, where hundreds of monks collect rice from kneeling devotees at sunrise, is profoundly moving.\n\nMount Phou Si at the town's centre offers panoramic Mekong views and a gilded stupa. The night market along Sisavangvong Road is one of Southeast Asia's most atmospheric bazaars.",
        {"UNESCO":"World Heritage Site (1995)","Key Ritual":"Tak bat alms-giving (sunrise daily)","Temples":"34 active wats","Best Time":"November–February","River":"Mekong & Nam Khan confluence"},
        "Temples generally open 8:00 AM – 5:00 PM","Free to explore; temple donations appreciated","19.8857° N, 102.1338° E",
        "Stand back and observe the tak bat ceremony respectfully — intrusive photography or touching monks is deeply disrespectful."),
      _d("kuang-si-falls","Kuang Si Falls","Luang Prabang Province","Turquoise Waterfall","kuang+si+falls+laos+turquoise+waterfall+pool+lush+jungle",
        "A multi-tiered cascade of electric turquoise water tumbling through lush jungle into swimmable terraced pools of vivid blue-green.",
        "Kuang Si's three-tiered waterfall descends 50 metres through limestone formations into a series of naturally terraced pools coloured an extraordinary aquamarine by dissolved minerals. The pools are swimmable and the surrounding forest is home to rescued Asiatic black bears.\n\nThe 30-kilometre journey from Luang Prabang passes through hill tribe villages. Arriving early morning guarantees a quieter, more magical experience before tour groups arrive by midday.",
        {"Height":"50 m total drop","Water Colour":"Turquoise (dissolved calcium carbonate)","Swimming":"Yes (lower pools)","Nearby":"Bear rescue sanctuary","Distance":"29 km from Luang Prabang"},
        "8:00 AM – 5:30 PM daily","LAK 20,000 (≈ USD 1) adult","19.7312° N, 101.9855° E",
        "Arrive at 8 AM opening for near-solitary access to the pools — the site fills completely with day tours by 10 AM."),
      _d("vang-vieng","Vang Vieng","Vientiane Province","Karst Riverside Town","vang+vieng+laos+karst+mountains+nam+song+river+kayak",
        "A dramatic riverside town encircled by limestone karst towers, where kayaking, tubing, and cave exploration meet the Nam Song River.",
        "Vang Vieng's setting is one of Southeast Asia's most photogenic — the Nam Song River winds between vertical karst peaks that glow gold at sunrise and dissolve into silhouette at dusk. The town has transformed from a party destination into a more balanced adventure base.\n\nBlue Lagoon 1 and 2 offer swimming in clear spring-fed pools beneath karst cliffs. Tham Chang cave accessible directly from town provides an introduction to Vang Vieng's extraordinary limestone underworld.",
        {"Setting":"Karst limestone valley, Nam Song River","Activities":"Kayaking, tubing, caving, cycling","Blue Lagoons":"3 accessible sites","Best Time":"November–March","Distance":"160 km from Vientiane"},
        "Sites open from 8:00 AM – 6:00 PM","Blue Lagoon entry LAK 10,000","18.9247° N, 102.4483° E",
        "Kayak north from town and float back — the karst panorama seen from the water at sunset is completely different from any road view."),
      _d("plain-of-jars","Plain of Jars","Xieng Khouang","Megalithic Site","plain+of+jars+laos+megalithic+stone+jars+mysterious+plateau",
        "A mysterious highland plateau strewn with thousands of ancient stone jars whose origin and purpose remain one of Southeast Asia's great archaeological enigmas.",
        "The Plain of Jars spans 90 sites across the Xieng Khouang Plateau, where stone jars up to 3 metres tall and 10 tonnes in weight were placed between 500 BCE and 500 CE, likely as funerary urns. The UNESCO-listed Site 1 alone contains over 300 jars.\n\nThe plateau is heavily cratered from American bombing during the Vietnam War, and UXO clearance continues — visitors must remain on marked paths at all sites. The combination of ancient mystery and 20th-century history gives the site a haunting, layered significance.",
        {"UNESCO":"World Heritage Site (2019)","Sites":"90+ (3 major visitor sites)","Jar Count":"Site 1: 300+ jars","Era":"500 BCE – 500 CE","Warning":"UXO — stay on marked paths only"},
        "8:00 AM – 5:00 PM daily","USD 5 adult","19.4500° N, 103.1667° E",
        "Visit sites 1, 2, and 3 in a single day trip from Phonsavan — a local guide adds essential historical and bomb-era context."),
      _d("vientiane-pha-that-luang","Pha That Luang","Vientiane","National Symbol","pha+that+luang+vientiane+laos+golden+stupa+national+monument",
        "Laos's most sacred monument and national symbol, a towering gold stupa enclosing a relic of the Buddha at the heart of the capital.",
        "Pha That Luang — the 'Great Sacred Stupa' — rises 45 metres above Vientiane and has stood as Laos's spiritual and national heart since King Setthathirath moved the capital here in 1560. The current structure was rebuilt by the French in 1900 after being looted by Thai forces.\n\nThe complex is surrounded by the ruins of two smaller temples and beautiful gardens. The That Luang Festival each November draws thousands of monks and worshippers in one of Laos's most important Buddhist celebrations.",
        {"Height":"45 m","Built (current)":"1900 (on 16th-c. foundations)","Significance":"Laos's national monument","Festival":"That Luang (November full moon)","Distance":"4 km from central Vientiane"},
        "8:00 AM – 12:00 PM, 1:00 PM – 4:00 PM (closed Mon & Fri AM)","LAK 10,000 adult","17.9745° N, 102.6021° E",
        "Dress modestly — shoulders and knees covered are required — and remove shoes before entering any of the inner sanctuaries.")
  ]),
  "kazakhstan":_c("kazakhstan","Kazakhstan",48.02,66.92,"Central Asia","48.0196° N, 66.9237° E",
    "The world's largest landlocked country, a land of infinite steppe, dramatic red canyons, alpine lakes, and the echoes of Soviet space-race ambition.",
    "Steppe / Canyon / Mountain","Continental Semi-Arid","Eurasian Steppe & Montane Forest",[
      _d("charyn-canyon","Charyn Canyon","Almaty Region","Grand Canyon of Central Asia","charyn+canyon+red+rock+formations+valley+grand+kazakhstan",
        "A 90-kilometre canyon of flaming red and orange rock formations carved by the Charyn River, often called the Grand Canyon of Central Asia.",
        "Charyn Canyon's Valley of Castles section presents a 2-kilometre walk between pillars and turrets of red sedimentary rock eroded over 12 million years. The canyon reaches 300 metres deep, and its walls glow vivid orange and red at sunrise and sunset.\n\nThe Charyn River at the canyon floor can be reached by trail for swimming in summer. The canyon is a straightforward day trip from Almaty through sweeping Kazakh steppe dotted with wild apple trees.",
        {"Length":"90 km total","Max Depth":"300 m","Age":"12 million years","Best Time":"April–June, Sep–Oct","Distance":"215 km from Almaty"},
        "Open year-round; best daylight hours","KZT 1,000 entry","43.3500° N, 79.0833° E",
        "The Valley of Castles walk is 2 km one-way — wear solid shoes as the path descends loose rock and gets very hot midday."),
      _d("kolsai-lakes","Kolsai Lakes","Almaty Region","Alpine Lakes","kolsai+lakes+kazakhstan+alpine+turquoise+forest+mountains",
        "Three glacially-fed alpine lakes stepping up a forested Tian Shan valley in hues of emerald and turquoise that deepen with altitude.",
        "The Kolsai Lakes cascade through spruce forest at 1,800 to 2,850 metres elevation in the Northern Tian Shan, the upper lake sitting just 12 kilometres from the Kyrgyzstan border. The water clarity is exceptional, reflecting surrounding peaks and sky in mirror perfection.\n\nHorse riding connects the three lakes for those who prefer not to hike. The area is increasingly popular with Almaty weekenders but retains a wilderness character on weekday visits.",
        {"Lakes":"3 (Lower, Middle, Upper)","Elevation":"1,818–2,850 m","Mountains":"Northern Tian Shan","Best Time":"June–September","Activity":"Hiking, horse riding, camping"},
        "Open year-round; lower lake accessible all year","KZT 1,000 park entry","42.9833° N, 78.3167° E",
        "The middle lake has the best combination of scenery and accessibility — allow 3 hours for the hike from the lower lake."),
      _d("medeo-skating-rink","Medeo Mountain Stadium","Almaty","Mountain Sports Complex","medeo+almaty+kazakhstan+mountain+stadium+winter+snow+dam",
        "The world's highest outdoor speed-skating rink at 1,691 metres, backed by Tian Shan glaciers and a dramatic flood-control dam.",
        "Built in 1972 and legendary in Soviet-era speed skating for its record-breaking altitude ice, Medeo sits in a dramatic mountain gorge just 15 kilometres from downtown Almaty. The rink transforms into a public skating venue in winter.\n\nA staircase of 842 steps climbs the flood-control dam above Medeo to the Shymbulak Ski Resort, making it a year-round mountain recreation complex. Summer visitors use it as a starting point for Zailiysky Alatau mountain hikes.",
        {"Elevation":"1,691 m","Built":"1972 (Soviet era)","Winter":"Public skating (Dec–Feb)","Nearby":"Shymbulak Ski Resort (above)","Distance":"15 km from Almaty centre"},
        "Winter skating 10:00 AM – 10:00 PM; summer 9:00 AM – 8:00 PM","KZT 1,500 winter skating","43.1561° N, 77.0583° E",
        "Take the gondola up from Shymbulak in summer for Tian Shan views — the upper station at 3,200 m overlooks glaciers."),
      _d("baikonur-cosmodrome","Baikonur Cosmodrome","Kyzylorda Region","Space Launch Site","baikonur+cosmodrome+kazakhstan+rocket+launch+space+soyuz",
        "The world's first and largest operational space launch facility, where Sputnik, Gagarin, and every Soyuz mission to the ISS have lifted off.",
        "Baikonur Cosmodrome has been the launchpad for human space exploration since 1957, when Sputnik became the first artificial satellite launched from its pads. Yuri Gagarin departed from here in 1961 on humanity's first crewed spaceflight.\n\nRussia leases the facility from Kazakhstan, and Soyuz rockets continue to launch here on missions to the International Space Station. Organised tours allow visitors to watch launches up close — one of the most viscerally awe-inspiring spectacles on Earth.",
        {"Founded":"1955","Historic Launch":"Sputnik 1957, Gagarin 1961","Area":"6,717 km²","Operator":"Roscosmos (leased from Kazakhstan)","Tours":"Available via specialist agencies"},
        "Access by tour only; launch schedules vary","USD 1,000–2,000 per launch tour","45.9646° N, 63.3052° E",
        "Book a launch viewing tour 6–12 months in advance — Soyuz launch schedules are published well ahead and spots fill immediately."),
      _d("burabay-national-park","Burabay National Park","Akmola Region","Lake Forest Resort","burabay+national+park+kazakhstan+blue+lake+granite+pine+forest",
        "Kazakhstan's beloved 'Swiss of the Steppe', where granite islands and pine forests rise improbably from the flat steppe beside sparkling blue lakes.",
        "Burabay National Park protects a landscape of extraordinary geological contrast — ancient granite outcrops including the iconic Okzhetpes and Blue Bay Sphinx rise from pine forests beside three major lakes in the midst of open steppe. It has been a resort and sanatorium destination since tsarist times.\n\nBoating, hiking, and horse riding are the main activities in summer, while the park turns into a winter cross-country skiing destination. Numerous legends of the Kazakh national hero Abylay Khan are tied to the distinctive rock formations.",
        {"Area":"129,000 hectares","Lakes":"Burabay, Shuchye, Korolevskoe","Key Rock":"Okzhetpes ('Arrow Cannot Pass')","Distance":"250 km from Nur-Sultan (Astana)","Best Time":"June–August, January–February"},
        "Open year-round; park entrance 8:00 AM – 8:00 PM","KZT 500 entry","53.0833° N, 70.2667° E",
        "Rent a paddle boat on Lake Burabay for the best close-up view of the granite formations rising from the water.")
  ]),
  "saudi-arabia":_c("saudi-arabia","Saudi Arabia",23.89,45.08,"Middle East","23.8859° N, 45.0792° E",
    "An ancient desert kingdom newly opened to the world, where Nabataean tombs rival Petra, colossal sand seas stretch to the horizon, and Vision 2030 transforms a closed civilisation into a destination.",
    "Desert / Mountain / Coastal","Hot Desert","Arabian Desert & Red Sea Coast",[
      _d("alula-heritage-site","AlUla Heritage Site","Al-Ula Province","Ancient Nabataean City","alula+saudi+arabia+hegra+nabataean+rock+tombs+rose+canyon",
        "A vast ancient landscape of Nabataean tomb cities, sandstone canyons, and 200,000-year-old human history in Arabia's most dramatic setting.",
        "AlUla encompasses Hegra — Saudi Arabia's first UNESCO World Heritage Site — where over 100 Nabataean rock-cut tombs stand 20 metres tall in rose-coloured sandstone canyons. The tombs date from the 1st century BCE and rival Petra in architectural grandeur.\n\nThe surrounding landscape of Elephant Rock, Jabal Ikmah's ancient inscriptions, and the mirrored Maraya concert hall adds further layers of wonder. AlUla only opened to international tourists in 2019 and remains one of the world's great uncrowded wonders.",
        {"UNESCO":"Hegra World Heritage Site (2008)","Tombs":"100+ Nabataean rock-cut tombs","Era":"1st century BCE – 1st century CE","Best Time":"November–March","Opened to Tourists":"2019"},
        "Tours depart 8:00 AM – 5:00 PM; tickets required","SAR 95 adult (Hegra site)","26.7152° N, 37.9753° E",
        "Book Hegra entry tickets online well in advance — daily visitor numbers are capped to protect the site."),
      _d("madain-saleh","Madain Saleh (Hegra)","Al-Ula Province","Rock-Cut Tombs","madain+saleh+saudi+arabia+nabataean+tombs+hegra+desert",
        "Saudi Arabia's Petra — a Nabataean necropolis of monumental carved facades rising from golden desert plains in eerie, magnificent solitude.",
        "Madain Saleh, the ancient name for Hegra, was the Nabataean kingdom's second city after Petra, a thriving caravan hub on the incense route. The 131 surviving rock-cut tombs are astonishingly well-preserved by the dry desert climate.\n\nUnlike Petra, Madain Saleh sees only a fraction of the visitors, giving the site an unmatched atmosphere of solitary grandeur. The Jabal Ithlib area holds temples and a dining hall carved into natural sandstone formations.",
        {"Ancient Name":"Hegra","Era":"Nabataean (1st c. BCE – 1st c. CE)","Tombs":"131 preserved facades","UNESCO":"World Heritage Site (2008)","Visitors":"Limited (uncrowded)"},
        "Tours: 8:00 AM – 5:00 PM (advance booking required)","Included in AlUla pass (SAR 95)","26.8000° N, 37.9500° E",
        "The tombs in golden hour light are extraordinary — arrange the earliest morning tour slot for the best photography conditions."),
      _d("edge-of-the-world-riyadh","Edge of the World","Riyadh Province","Dramatic Escarpment","edge+of+world+riyadh+saudi+arabia+escarpment+dramatic+cliff+desert",
        "A vertiginous cliff edge 300 metres above an infinite flat desert plain, where Arabia's geological drama is laid bare in total silence.",
        "Jebel Fihrayn — the 'Edge of the World' — is a dramatic escarpment at the northwestern rim of the Tuwaiq Mountains, where the plateau abruptly terminates in a 300-metre vertical cliff overlooking a vast, featureless plain. The horizon stretches endlessly on clear days.\n\nThe site requires a 4WD drive across 40 kilometres of desert track from the Riyadh-Sudair highway. Sunset at the cliff edge, with shadows pooling in the valley far below and silence broken only by wind, is one of Saudi Arabia's most profound experiences.",
        {"Height":"300 m escarpment","Rock Type":"Tuwaiq limestone (Jurassic)","Access":"4WD required (40 km off-road)","Distance":"75 km from central Riyadh","Best Time":"October–April, sunset visit"},
        "Open year-round (daylight recommended)","Free","24.4917° N, 46.1583° E",
        "Go with a guide who knows the track — the route across featureless desert is easy to get lost on without GPS waypoints."),
      _d("rub-al-khali-desert","Rub' al-Khali Desert","Multiple Provinces","World's Largest Sand Desert","rub+al+khali+empty+quarter+saudi+arabia+massive+sand+dunes+orange",
        "The world's largest continuous sand desert — 650,000 square kilometres of colossal orange dunes that dwarf all other sand seas on Earth.",
        "The Empty Quarter covers a quarter of the Arabian Peninsula with dunes reaching 250 metres — higher than the Eiffel Tower — in total, bone-dry solitude. The sand shifts from cream white to deep blood orange depending on iron oxide content.\n\nExplorer Wilfred Thesiger crossed it twice in the 1940s in journeys now considered among the greatest feats of desert travel. Modern visitors access the dunes near Shaybah or from the UAE side, typically on 4WD and camel expeditions.",
        {"Area":"650,000 km² (world's largest sand desert)","Max Dune Height":"250 m","Countries":"Saudi Arabia, UAE, Oman, Yemen","Annual Rainfall":"Under 35 mm","Best Time":"November–February"},
        "No fixed access; expedition-based entry","Expedition tours from USD 300/day","21.0000° N, 51.0000° E",
        "Join an organised 4WD expedition from Riyadh or Abu Dhabi — self-navigation in the Empty Quarter without a guide is genuinely life-threatening."),
      _d("diriyah-historic","Diriyah Historic District","Riyadh Province","Saudi Dynasty Birthplace","diriyah+saudi+arabia+historic+mudbrick+first+saudi+state+walls",
        "The mud-brick birthplace of the Saudi dynasty and the First Saudi State, a UNESCO-listed oasis town now dramatically restored on the outskirts of Riyadh.",
        "Diriyah's At-Turaif District is a UNESCO World Heritage Site and the ancestral home of the Al Saud family, where the First Saudi State was founded in 1727 in alliance with the reformist cleric Muhammad ibn Abd al-Wahhab. The distinctive Najdi mud-brick architecture — with its buttressed walls and geometric detailing — is uniquely Arabian.\n\nA major restoration and cultural development project has transformed Diriyah into a world-class heritage destination with museums, restaurants, and cultural events. The Wadi Hanifa oasis setting adds green palms against ochre mud-brick in a striking visual contrast.",
        {"UNESCO":"At-Turaif World Heritage Site (2010)","Founded":"1727 (First Saudi State)","Architecture":"Najdi mud-brick","Distance":"20 km from central Riyadh","Development":"Ongoing Vision 2030 project"},
        "9:00 AM – 10:00 PM (Thu–Sat until midnight)","SAR 49 adult (At-Turaif)","24.7341° N, 46.5753° E",
        "Visit on a weekday evening when the site is lit beautifully and the Wadi Hanifa setting can be enjoyed without weekend crowds.")
  ])
};
if(window.COUNTRIES_DATA)Object.assign(window.COUNTRIES_DATA,more);
else window.COUNTRIES_DATA=more;
})();
